### ISSUE TITLE
New type in serializer

### ISSUE THREAD

**Issue by jmaquet** [rapl/rapl#8]
Hi there !

We are testing your bundle for a project in our company.
I added a type in the serializer, i forked your project and added it  here : https://github.com/jmaquet/rapl/commit/f1eceb4bb7a28205fd641387f853b2dd9ef7f41e

I did that because we have an entity user, a user has an adress, but the adress is an array. We were not able to load it in our User entity. We tried to create an adress entity and bind our array on the entity, it almost worked except that our array doesn't have any ID so doctrine refused our entity.

The only solution i found is the commit just above. Do you see any problem with this? Do you think this could be included directly in your code?

Thanks !

**Comment by nicwortel** [comment]
Hi Julien,

Thank you for opening this issue.

I think that the way RAPL handles data types should be refactored so you can add custom ones, similar to the way Doctrine handles this.

This would allow you to create an `Address` value object, which is mapped to an array. Of course you can also just use an array in your entities, but using value objects is probably better.

I'll look into this when I find some time.

**Comment by nicwortel** [comment]
@jmaquet I've merged a commit into master that should allow the use of arrays as well as the use of value objects.

For arrays, a new `array` type is introduced.

For value objects, you can create custom types by extending the [`Type`](https://github.com/rapl/rapl/blob/master/src/Types/Type.php) class. Override the `convertToSerializedValue` and `convertToPhpValue` methods to map your value object to the serialized representation and vice versa. Take a look at the [`DateTimeType`](https://github.com/rapl/rapl/blob/master/src/Types/DateTimeType.php) if you're looking for an example. Don't forget to call `\RAPL\RAPL\Types\Type::addType('yourcustomtype', 'Your\Custom\Type');` to register your custom type in RAPL.

Let me know if something is not working correctly or when you have any questions.
